### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 accountChanged listeners added. 

### ISSUE THREAD

**Issue by deAgora** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#10]
Hi fellows and @PatrickAlphaC ,

I am working off of the instructions in the video specifically pertaining to the connectbutton (either/both the ManualHeader and Header versions) in a blank project of my own.

Scope of the problem:  I ONLY have the Header component in my project and I add an option to go back and forth between pages (via a standard barebones navbar (using next/link) I notice that after a couple of pageloads that the following error pops up: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 accountChanged listeners added. 

This happens when loading the ManualHeader or the Header and there are no other components built/loaded so it is only the verbatim Header Component that handles the connectbutton (meaning that the problem originates here and not from any other component that I personally concocted). I realise this does not directly relate to the course perse however should other viewers want to branch out on their own this is potentially gonna cause problems. 

For anyone branching out on your own; did you run into similar problems? If yes how did you fix it? Is the connectbutton not working properly or does it not 'play nice' with the next/Link router?

Any and all comments are welcome!

Kind Regards,

Patrick

**Comment by PatrickAlphaC** [comment]
Hello!

Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by deAgora** [comment]
Wilco, thank you for reaching out
