### ISSUE TITLE
Unhandled Runtime Error when trying to view the entrance fee in the browser

### ISSUE THREAD

**Issue by Sanchez7599** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#11]
I'm getting the error below when trying to convert entrance fee to string.

![image](https://user-images.githubusercontent.com/109904315/185800164-baf07d9c-3ede-41db-ae6e-33a8c5e353d6.png)

This is my LotteryEntrance.js

```
import { useEffect, useState } from "react"
import { useMoralis } from "react-moralis"
import { useWeb3Contract } from "react-moralis"
import { abi, contractAddresses } from "../constants"
import { ethers } from "ethers"

export default function LotteryEntrance() {
    const { chainId: chainIdHex, isWeb3Enabled } = useMoralis()
    const chainId = parseInt(chainIdHex)
    const raffleAddress = chainId in contractAddresses ? contractAddresses[chainId][0] : null

    const [entranceFee, setEntranceFee] = useState("0")

    // const {runContractFunction: enterRaffle} = useWeb3Contract({
    //     abi: abi,
    //     contractAddress: raffleAddress,
    //     functionName: "enterRaffle",
    //     params: {},
    //     msgValue:
    // })

    const { runContractFunction: getEntranceFee } = useWeb3Contract({
        abi: abi,
        contractAddress: raffleAddress,
        functionName: "getEntranceFee",
        params: {},
    })

    useEffect(() => {
        if (isWeb3Enabled) {
            async function updateUI() {
                const entranceFeeFromCall = (await getEntranceFee()).toString()
                setEntranceFee(ethers.utils.formatUnits(entranceFeeFromCall, "ether"))
            }
            updateUI()
        }
    }, [isWeb3Enabled])

    return (
        <div>
            Hi<div>{entranceFee}</div>
        </div>
    )
}
```

I'm couple of hours into this issue, still can't figure it out. Anyone having the same issue?

**Comment by Sanchez7599** [comment]
Also, I know that `entranceFee` is fine in my Raffle contract because I deployed it on rinkeby and called `getEntranceFee` function:

![image](https://user-images.githubusercontent.com/109904315/185801000-a5de97c9-3926-49b3-9e04-c1d4682ab675.png)

**Comment by Sanchez7599** [comment]
I wrote LotteryEntrance.js again and it works.

I never figured out what was wrong.

**Comment by Puchacz1** [comment]
I have same issue :(

**Comment by BornaBM** [comment]
I rewrote it and it still doesn't work :/

**Comment by vasubhrdwj** [comment]
You are quite possibly using a wrong chain, Make sure you are connected to Hardhat local host and make sue you run node in your terminal

**Comment by Maroutis** [comment]
Be sure to be on Hardhat localhost network on Metamask. At this point the sepolia address is not added to the constants.
