### ISSUE TITLE
Issue when swaping on mumbai test net

### ISSUE THREAD

**Issue by Puchacz1** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#15]
i follow whole  course on goerli and everything works fine, but when i change to mumbai i get this error every time:
![image](https://user-images.githubusercontent.com/110934149/189038403-c1c1738d-565b-468e-96c1-676764546a45.png)
and it happens only on web ui because on polyscan i can call enter raffle without trouble: 
https://mumbai.polygonscan.com/address/0xda21DAb48D0DCfb40D69A133356f8303979A79ea#writeContract
I tried reseting account and reinstaling metamask.
I will be grateful for help ;)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
