### ISSUE TITLE
failed to run scripts/mockOffchain.js

### ISSUE THREAD

**Issue by wangyangv1** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#16]
![image](https://user-images.githubusercontent.com/49341812/189884168-12f2702e-8b63-4f49-b1d9-a9ecf5060071.png)
I copied the contents of scripts/mockOffchain.js directly from github

But when I run this script, vscode throws the following error

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by Kunal-Khatri-1** [comment]
Check your **hardhat.config.js file** for the project. Did you **add the localHost network** with the correct **chainId**?
```
networks: {
        hardhat: {
            chainId: 31337,
            blockConfirmations: 1,
        },
        goerli: {
            chainId: 5,
            blockConfirmations: 6,
            url: GOERLI_RPC_URL,
            accounts: [PRIVATE_KEY],
        },
        localhost: {
            chainId: 31337,
        },
    `},
```

**Comment by MrAbuz** [comment]
> Check your **hardhat.config.js file** for the project. Did you **add the localHost network** with the correct **chainId**?
> 
> ```
> networks: {
>         hardhat: {
>             chainId: 31337,
>             blockConfirmations: 1,
>         },
>         goerli: {
>             chainId: 5,
>             blockConfirmations: 6,
>             url: GOERLI_RPC_URL,
>             accounts: [PRIVATE_KEY],
>         },
>         localhost: {
>             chainId: 31337,
>         },
>     `},
> ```

This worked for me! Thanks a lot :)

**Comment by MrAbuz** [comment]
@Kunal-Khatri-1 This worked for me! Super easy but I wasn't figuring it out. Thanks a lot :)
