### ISSUE TITLE
Lesson10: Unrecognized-selector

### ISSUE THREAD

**Issue by pacmac0** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#23]
When trying to call the enterLottery function of the contract on hardhat local test-net I get an error in the HH node console:

eth_call
Contract call:       Raffle#<unrecognized-selector>
From:                   0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
To:                       0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9
Error: Transaction reverted: function selector was not recognized and there's no fallback function at Raffle.<unrecognized-selector> (contracts/Raffle.sol:22)

This is reappearing multiple times then.

I found the issue being discussed here: https://github.com/MetaMask/metamask-extension/issues/14963
But the final conclusion seemed to be to reset the Metamask account, which I tried but seems not to work for me. 
Did I miss some other part of the discussion that needs to be taken into account? Is anyone else still having that issue?

The other getter functions do work and the UI does even update the "numberOfPlayers" field. Also, the account balance is being reduced. I'm not sure if that means, that the transaction is actually executed and the hh node messages are wrong.

Thanks for your help!

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
