### ISSUE TITLE
WebSocket connection is closed before connection

### ISSUE THREAD

**Issue by achimstruve** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#31]
Hi,
I am getting these warnings in my console. Just started with the exploration of the useEffect function, but the warnings come regardless if I have the useEffect function in my code or not.
Regarding the first warning about the DevTools, I found already a solution by google it.

Does someone know how to prevent these annoying warnings?

![image](https://user-images.githubusercontent.com/25647387/215539662-dcbc4df5-173d-4e7e-9ad9-05d64b069b84.png)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by achimstruve** [comment]
Thanks for answering Patrick,
The error doesn't occur anymore after I restarted my laptop.

Sorry for the question being not as readable as it should be. Should've been more specific about my current state in the project + sharing some code next time, I guess.
