### ISSUE TITLE
Problem with importing: Module not found: Can't resolve 'next/font/google'

### ISSUE THREAD

**Issue by radupt** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#36]
Hi everyone,
I'm having this error when running:
`yarn dev`
error:
`Module not found: Can't resolve 'next/font/google'
  1 | import Head from "next/head"
  2 | import Image from "next/image"
> 3 | import { Inter } from "next/font/google"
  4 | import styles from "@/styles/Home.module.css"
  5 | import ManualHeader from "../Compones/ManualHeader"
  6 | `

Any ideas of why??

**Comment by Davelop4** [comment]
Hi
Make sure you are using the same dependecies in package.json at the repo
remove this line... import { Inter } from "next/font/google", use import styles from "../styles/Home.module.css"
