### ISSUE TITLE
Module not found: Can't resolve 'moralis-v1'

### ISSUE THREAD

**Issue by tuagkcuf** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#38]
Seems that the code for moralis is deprecated.

**Comment by PatrickAlphaC** [comment]
Correct. Please use the graph integration

**Comment by hariprasad9899** [comment]
> ct. Please use the graph integration

Hello Patrick, What exactly is graph integration? I am facing the same issue and could you please provide more input on this?
