### ISSUE TITLE
Lesson 10: Nextjs-smartcontract-lottery hosting error on fleek

### ISSUE THREAD

**Issue by yash-mittal-2003** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#39]
[https://github.com/shy-orpheus/nextjs-smartcontract-lottery-yash](url) this is my code repository that I have made while following along this lesson, but I am getting an error while hosting on fleek the screenshot of which is as follows:

![image](https://user-images.githubusercontent.com/110320507/235353995-22cd9991-3bc9-4418-88fa-09284edf3045.png)

could someone please help me debug the same, it would be a huge help, thanks!

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by hariprasad9899** [comment]
Hi, 
Do you find the solution to this prob?  
I don't find any separate thread of this in https://github.com/smartcontractkit/full-blockchain-solidity-course-js/

Please help

**Comment by yash-mittal-2003** [comment]
Yes, you can delete the node_modules folder and the yarn.lock folder and run yarn again.
It worked for me.
