### ISSUE TITLE
Fleek Hosting: error Found incompatible module:

### ISSUE THREAD

**Issue by Sammycoderr** [PatrickAlphaC/nextjs-smartcontract-lottery-fcc#49]
`The engine "node" is incompatible with this module. Expected version ">=16.18.1". Got "16.4.2"`

I mean I've had a similar problem, in fact, an exact problem locally, but I somehow found a way to upgrade `node`. But I do not know what to do here.

I'd appreciate your urgent help please @PatrickAlphaC and others.
thanks.

![Screenshot (51)](https://github.com/PatrickAlphaC/nextjs-smartcontract-lottery-fcc/assets/86566548/81d89af2-eb82-4caf-87d9-7851707bbe93)

**Comment by Sammycoderr** [comment]
anyone please?

**Comment by PatrickAlphaC** [comment]
Try out node version manager!

https://www.freecodecamp.org/news/node-version-manager-nvm-install-guide/

You're using an outdated version of node.
